export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const NEW_JOIN_ROOM_DATA = 'NEW_JOIN_ROOM_DATA';
export const NEW_MEETING_CALL_FRAME = 'NEW_MEETING_CALL_FRAME';
export const ROOM_MEETING_VIEW_NAME = 'ROOM_MEETING_VIEW_NAME';
export const ALL_ROOM_MEETING_PARTICIPANT_DATA = 'ALL_ROOM_MEETING_PARTICIPANT_DATA';
export const ALL_USERS_IN_CALL = 'ALL_USERS_IN_CALL';
export const ALL_CALL_LOG_DATA = 'ALL_CALL_LOG_DATA';
export const CURRENT_CALL_SPEECH_TO_TEXT = 'CURRENT_CALL_SPEECH_TO_TEXT';
export const ACTIVE_SPEAKING_USER_DATA = 'ACTIVE_SPEAKING_USER_DATA';

export const ALL_USER_DATA_SUCCESS = 'ALL_USER_DATA_SUCCESS';
export const ALL_ADMIN_DATA_SUCCESS = 'ALL_ADMIN_DATA_SUCCESS';
