export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const NEW_JOIN_ROOM_DATA = 'NEW_JOIN_ROOM_DATA';
export const NEW_MEETING_CALL_FRAME = 'NEW_MEETING_CALL_FRAME';
export const ROOM_MEETING_VIEW_NAME = 'ROOM_MEETING_VIEW_NAME';
export const ALL_ROOM_MEETING_PARTICIPANT_DATA = 'ALL_ROOM_MEETING_PARTICIPANT_DATA';
export const ALL_USERS_IN_CALL = 'ALL_USERS_IN_CALL';
export const ALL_CALL_LOG_DATA = 'ALL_CALL_LOG_DATA';
export const CURRENT_CALL_SPEECH_TO_TEXT = 'CURRENT_CALL_SPEECH_TO_TEXT';
export const ACTIVE_SPEAKING_USER_DATA = 'ACTIVE_SPEAKING_USER_DATA';
export const ALL_USER_DATA_SUCCESS = 'ALL_USER_DATA_SUCCESS';
export const CALL_SOCKET_MESSAGE_BROADCAST = 'CALL_SOCKET_MESSAGE_BROADCAST';
export const MY_CURRENT_AUDIO_CHANGE = 'MY_CURRENT_AUDIO_CHANGE';
export const NEW_ADDED_USER_IN_CALL_DATA = 'NEW_ADDED_USER_IN_CALL_DATA';
export const NEW_LEAVE_USER_IN_CALL_DATA = 'NEW_LEAVE_USER_IN_CALL_DATA';


//////// TEMP //////////////
export const CURRENT_ROOM_DETAILS = 'CURRENT_ROOM_DETAILS';
//////// TEMP //////////////
